In [ ]:
import numpy as np

data = np.array([
    22.5, 23.1, -999,  21.8, np.nan, 24.0,
    150.0, 22.9, 23.5, np.nan, -5.2, 22.1,
    23.8, np.nan, 999.9, 21.5, 22.7, -50.0,
    23.0, 22.4
])

nanvalue=np.isnan(data)
rows = np.where(nanvalue)[0]
positions = list(zip(rows))
print(positions)

negvalue = data < 0
rowsN = np.where(negvalue)[0]
positionsN = list(zip(rowsN))
print(positionsN)

mean=np.nanmean(data)
std=np.nanstd(data)
scores=(data-mean)/std
number=data[np.abs(scores)>2]
print(number)

badvalues=nanvalue | negvalue |

[(4,), (9,), (13,)]
[(2,), (10,), (17,)]
[-999.   999.9]


In [36]:
import numpy as np

tableau = np.array([[np.nan, 15, 89, 60, np.nan],
                    [np.nan, 15, 89, 60, np.nan]])
nanvalue = np.isnan(tableau)
rows,columns=np.where(nanvalue)
positions=list(zip(rows,columns))
print(positions)
print(len(positions))
moy_general=np.nanmean(tableau)
tableau_clean=tableau.copy()
tableau_clean[nanvalue]=moy_general
print(tableau_clean)

[(0, 0), (0, 4), (1, 0), (1, 4)]
4
[[54.66666667 15.         89.         60.         54.66666667]
 [54.66666667 15.         89.         60.         54.66666667]]


In [20]:
import numpy as np 

tableau=np.array([12, 48, 49, 16, 72, 36, 26, 46])

seuil_max=50
seuil_min=20

mes_normal=(tableau>seuil_min) & (tableau<seuil_max)
mes_sus=(tableau<seuil_min) | (tableau>seuil_max)

valeurNormal=tableau[mes_normal]
valeurSus=tableau[mes_sus]
nombreSus=np.size(valeurSus)
positionsSus=np.where(valeurSus)[0]

print(valeurNormal)
print(valeurSus)
print(nombreSus)
print(positionsSus)


ValueError: either both or neither of x and y should be given

In [6]:
import numpy as np

clients=np.random.randint(1,50,size=[4,4])
clients_agée=clients[clients>30]
print(clients_agée)

[42 46 48 33 38 46 47 34 49]


In [7]:
import numpy as np

ventes=np.random.randint(100,500,size=[12,3])
ventes_total_columns=np.sum(ventes,axis=0)
moyenne_produit=np.mean(ventes,axis=0)
print(ventes_total_columns)
print(moyenne_produit)

ventes_total_mois=np.sum(ventes,axis=1)
moyenne_mois=np.mean(ventes,axis=1)
print(ventes_total_mois)
print(moyenne_mois)

meilleur_produit=np.argmax(ventes,axis=0)
meilleur_mois=np.argmax(ventes,axis=1)

print(meilleur_mois)
print(meilleur_produit)

[3238 3144 4273]
[269.83333333 262.         356.08333333]
[ 942 1002  973 1023  716  926  789 1119  831  682  735  917]
[314.         334.         324.33333333 341.         238.66666667
 308.66666667 263.         373.         277.         227.33333333
 245.         305.66666667]
[0 0 0 2 2 0 2 2 2 2 2 2]
[ 1  7 11]


In [8]:
import numpy as np

temperatures=np.random.randint(14,45,size=10)

moyenne=np.mean(temperatures)

jours_chauds=temperatures[temperatures>25]
jours_froids=temperatures[temperatures<25]
temp_sup_moyenne=temperatures[temperatures>moyenne]
amplitude_thermique=np.max(temperatures)- np.min(temperatures)

print(amplitude_thermique)
print(temperatures)
print(moyenne)
print(jours_chauds)
print(jours_froids)
print(temp_sup_moyenne)
print(amplitude_thermique)

17
[18 18 26 31 34 23 22 20 31 17]
24.0
[26 31 34 31]
[18 18 23 22 20 17]
[26 31 34 31]
17


In [9]:
import numpy as np

salaire_employee=np.random.randint(3500,8000,size=20)

moyenene=np.mean(salaire_employee)

median=np.median(salaire_employee)

ecart_type=np.std(salaire_employee)

min_salaire=np.min(salaire_employee)

max_salaire=np.max(salaire_employee)

q1=np.percentile(salaire_employee,25)

q2=np.percentile(salaire_employee,75)

print(q1)

5200.0


In [10]:
import numpy as np

ventes=np.random.randint(1000,9000,size=10)
print(ventes)
ca=np.sum(ventes)/np.size(ventes)
print(ca)

nombre_ventes=np.size(ventes)
max_ventes=np.max(ventes)
min_ventes=np.min(ventes)

vente_moyenne=np.mean(ventes)
print(vente_moyenne)

[4252 7050 1335 6113 6941 2595 1165 1875 2157 1263]
3474.6
3474.6


In [11]:
import numpy as np

clients = np.array([
    [1, 25, 80],
    [2, 30, 90],
    [3, 22, 70],
    [4, 28, 85]
])

clients[1][2]=85
clients[0]=[1, 55, 98]
clients[:,1]=[26, 31, 24, 29]


In [12]:
import numpy as np

clients=np.random.randint(18,50, size=(3, 4))
print(clients)

print(clients[0])
print(clients[:,0])
print(clients.dtype)
print(clients.shape[0])


[[40 34 44 28]
 [42 48 41 18]
 [19 23 49 36]]
[40 34 44 28]
[40 42 19]
int32
3


In [13]:
import numpy as np

jours=np.arange(10)

temperatures=np.linspace(5,12)

prix=np.zeros(7)

ids=np.ones(7)

prices=np.full([3,3],21)

print(jours)
print(temperatures)
print(prix)
print(ids)
print(prices)

print(jours.dtype)
print(temperatures.dtype)
print(prix.dtype)
print(ids.dtype)
print(prices.dtype)


[0 1 2 3 4 5 6 7 8 9]
[ 5.          5.14285714  5.28571429  5.42857143  5.57142857  5.71428571
  5.85714286  6.          6.14285714  6.28571429  6.42857143  6.57142857
  6.71428571  6.85714286  7.          7.14285714  7.28571429  7.42857143
  7.57142857  7.71428571  7.85714286  8.          8.14285714  8.28571429
  8.42857143  8.57142857  8.71428571  8.85714286  9.          9.14285714
  9.28571429  9.42857143  9.57142857  9.71428571  9.85714286 10.
 10.14285714 10.28571429 10.42857143 10.57142857 10.71428571 10.85714286
 11.         11.14285714 11.28571429 11.42857143 11.57142857 11.71428571
 11.85714286 12.        ]
[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]
[[21 21 21]
 [21 21 21]
 [21 21 21]]
int32
float64
float64
float64
int32


In [14]:
import numpy as np

notes=np.random.randint(5,20, size=(3, 5))
print(notes)

moyenne=np.mean(notes)
print(moyenne)

max_note=np.max(notes)
min_note=np.min(notes)
print("la meilleure et la plus faible note :", max_note , min_note)
print(" l'écart entre elles:",max_note-min_note)
note=notes[notes>moyenne]
print("les étudiants ayant obtenu une note supérieure à la moyenne:",note)

[[17 14 16  7 17]
 [ 5 14  7 18 12]
 [ 8  7  9 19 18]]
12.533333333333333
la meilleure et la plus faible note : 19 5
 l'écart entre elles: 14
les étudiants ayant obtenu une note supérieure à la moyenne: [17 14 16 17 14 18 19 18]


In [15]:
import numpy as np

tab1=np.random.randint(5000,size=10)
print(tab1)

print("Shape:",tab1.shape)
print("Dimensions:",tab1.ndim)
print("Size:",tab1.size)
print("Type:",tab1.dtype)

print(tab1[0])
print(tab1[-1])
print(np.min(tab1))
print(np.max(tab1))
print(np.mean(tab1))

[4174 4267 3305 2121 3092 4986 1424  842  604  533]
Shape: (10,)
Dimensions: 1
Size: 10
Type: int32
4174
533
533
4986
2534.8
