In [28]:
import numpy as np

a=np.array([
    [20, 3000, 800],
    [25, 5000, 1200],
    [30, 7000, 1500]
])

print(a.shape)

b=np.array([18,8000,1300])

res=a+b

print(res)

(3, 3)
[[   38 11000  2100]
 [   43 13000  2500]
 [   48 15000  2800]]
